model_provider = "custom"
model = "gpt-5.6"
model_reasoning_effort = "high"
disable_response_storage = true
sandbox_mode = "workspace-write"
model_catalog_json = "cc-switch-model-catalog.json"

[model_providers.custom]
name = "Sub2API"
base_url = "http://127.0.0.1:8079/v1"
wire_api = "responses"
requires_openai_auth = true
experimental_bearer_token = "PROXY_MANAGED"

[desktop]
followUpQueueMode = "queue"
show-context-window-usage = true
appearanceTheme = "dark"
appearanceLightCodeThemeId = "vercel"
sansFontSize = 16
codeFontSize = 16
appearanceDarkCodeThemeId = "nord"
conversationDetailMode = "STEPS_COMMANDS"
notifications-turn-mode = "always"

[desktop.appearanceLightChromeTheme]
accent = "#006aff"
contrast = 40
ink = "#171717"
opaqueWindows = true
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = '"Geist Mono", ui-monospace, "SFMono-Regular"'
ui = "Geist, Inter"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#28A948"
diffRemoved = "#EB001D"
skill = "#A100F8"

[desktop.appearanceDarkChromeTheme]
accent = "#88c0d0"
contrast = 60
ink = "#d8dee9"
opaqueWindows = false
surface = "#2e3440"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#a3be8c"
diffRemoved = "#bf616a"
skill = "#b48ead"

[windows]
sandbox = "elevated"

[projects.'d:\test\guan\eai-desktop']
trust_level = "trusted"

[projects.'d:\test\guan\zailin']
trust_level = "trusted"

[projects.'d:\test\work1']
trust_level = "trusted"

[plugins."figma@openai-api-curated"]
enabled = false

[plugins."impeccable@personal"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[marketplaces.openai-primary-runtime]
last_updated = "2026-08-19T01:00:38Z"
source_type = "local"
source = '\\?\C:\Users\观\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[sandbox_workspace_write]
network_access = true

[features]
memories = true

[memories]
generate_memories = true
use_memories = true
